name: Lighthouse CI
on: pull_request
jobs:
  lighthouse:
    runs-on: ubuntu-latest
    name: Measure Performance
    permissions:
      pull-requests: write

    steps:
      - uses: actions/checkout@v2
      - name: Wait for vercel
        uses: patrickedqvist/wait-for-vercel-preview@v1.1.1
        id: vercel
        with:
          token: ${{ secrets.GITHUB_TOKEN }}
          max_timeout: 120
      
      - name: Audit URLs using Lighthouse
        uses: treosh/lighthouse-ci-action@v8
        id: lighthouse
        with:
          urls: |
            ${{ steps.vercel.outputs.url }}
          temporaryPublicStorage: true
        env:
          LHCI_GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}

      - name: Parse Lighthouse output
        id: parse
        run: |
          echo "::set-output name=url::$(echo '${{ steps.lighthouse.outputs.links }}'| jq -r '.["${{ steps.vercel.outputs.URL }}/"]')"
     
      - name: Find Comment
        uses: peter-evans/find-comment@v1
        id: fc
        with:
          issue-number: ${{ github.event.pull_request.number }}
          comment-author: 'github-actions[bot]'
          body-includes: Lighthouse

      - name: Create comment
        uses: peter-evans/create-or-update-comment@v1
        with:
          comment-id: ${{ steps.fc.outputs.comment-id }}
          issue-number: ${{ github.event.pull_request.number }}
          body: |
            Check out the Lighthouse CI result:
            ${{ steps.parse.outputs.url }}
          edit-mode: replace

